[project]
name = "0x03-unittests-and-integration-tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "parameterized>=0.9.0",
    "requests>=2.32.4",
]
